### ISSUE TITLE
Реализовать новый метод авторизации (кроме БанкИД и ЭЦП) - "Емэил"

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1035]
- [x] 1) в массиве авторизаций (saAuth) привязываться к ИД "email"
- [x] 2) на кнопке писать "E-Mail"
- [x] 3) При нажатии на кнопку (п.2) отрисовывать диалог, с полем ввода электронного адреса(лейбл "Электронный адрес:") и кнопкой "Авторизоваться"
- [x] 4) после нажатия на кнопку "Авторизоваться" вызывать сервис verifyContactEmail ( https://github.com/e-government-ua/i/issues/1033 ) с передачей туда значения из поля "Электронный адрес" в параметр sQuestion и :
- при получении в ответе "bVerified: true" - заменять поле инпут с электронным адресом на лэйбл с этим адресом и добавлять новый инпут для ввода подтверждающего кода (с лейблом: "Код подтверждения:", кнопку "Подтвердить" и "Изменить адрес"(что возвратит на предыдущий шаг).
- при получении ответа: bVerified: false - выводить ошибку "невалидный электронный адрес"
- при получении ошибки- выводить ошибку "ошибка подтверждения электронного адреса"(и далее код ошибки)
- [x] 5) После нажатия кнопки "Подтвердить" передавать туда значения из поля "Электронный адрес" в параметр sQuestion и из поля "Код подтверждения" в параметр sAnswer:
- при получении ответа: bVerified: false - выводить ошибку "Вы ввели неверный код подтверждения"
- при получении ошибки- выводить ошибку "ошибка ввода кода подтверждения электронного адреса"(и далее код ошибки)
- при получении в ответе "bVerified: true" скрывать все поля и кнопки и переходить к п.6
- [x] 6) вызвать сервис /syncSubject ( https://github.com/e-government-ua/i/issues/1032 ) (он вызывался уже в коде для других авторизаций), передав туда в sCode_Subject - электронный адрес а в параметр nID_SubjectHumanIdType = 2 и так-же создать авторизационную сессию как и сейчас, запомнив полученный nID_Subject (как и сейчас)
- [x] 7) вызвать сервис /getSubjectHuman ( https://github.com/e-government-ua/i/issues/1034 ), с полученный в п.6. параметром nID_Subject
- [x] 8) Полученные Фамилию и Имя разместить в размещенные два поля-инпута с лейблами:
  Фамилия и Имя
- [x] 9) Только после заполненных полей п.8 (если они пришли пустыми гражданин должен будет их заполнить) - давать нажать кнопку "Войти" (ниже), иначе выводить диалог "Заполните все необходимые поля"
- [x] 10) Далее такое-же поведение как и сейчас (переход на форму заполнения полей услуги)

**Comment by AleksejDomash** [comment]
Привет, @vdubyna. Продолжил таску делать и не нашел бранча под неё. Если делаешь задачу, которая реально будет занимать большее кол-во времени, то пжлст создавай

**Comment by bvv4ik** [comment]
а я как раз наоборот, увожу коллег от отдельных бранчей) т.к., особенно в последнее время идет серьезны

**Comment by AleksejDomash** [comment]
В пункте 7 возвращается record not found. Передаю туда тот NID, который получил в пункте 6. При этом стоит отметить, что вызываю сервис getSubjectHuman

**Comment by sergeygorban** [comment]
Отчет о тестировании:
Тестирование проводилось на https://test.igov.org.ua/

1. При нажатии на кнопку Email, отображается только поле для ввода
электронного адреса и кнопка "Отримати код верифікації".
Согласно задачи https://github.com/e-government-ua/i/issues/1035, 
должно отображаться поле для ввода электронного адреса и кнопка "Авторизоваться"

2. При вводе не валидного электронного адреса и нажатии на кнопку "Отримати код верефікації" не выводится сообщение об ошибке.
3. При вводе электронного адреса типа qwer@1  и нажатии на кнопку "Отримати код верефікації" выполняется отправка кода
и появляется поле "Код верифікації", а также появляются кнопки "Підтвердити" и "Змінити електронну адресу"
4. При нажатии на кнопку "Підтвердити" без введенного кода подтверждения, сообщение об ошибке отсутствует
5. При вводе кода, отличного от того, который пришел на почту, появляются поля ввода фамилии, имени и отчества, а также появляются кнопки "Увійти"
и "Змінити електронну адресу"
6. Фамилию, имя и отчество можно ввести любыми символами
7. Авторизоваться и создать заявку можно используя разные электронные адреса и ФИО

**Comment by nazarenkod** [comment]
что с этой задачей? сейчас даже кнопка "Email" не отображается.

**Comment by AleksejDomash** [comment]
я сделал какрас процеса авторизации через почту. Дальше надо фиксить то, что нашли тестировщики. С пунктом 1 не согласен. Так, как сейчас, - правильно. Потому что получение кода на email, - это не "Авторизация"

**Comment by Koffeek** [comment]
@AleksejDomash а есть прогнозы, когда эти баги могут быть пофикшены?

**Comment by Koffeek** [comment]
Баги на данный момент:
1. При входе можно ввести любой код вместо кода авторизации и система пропускает на следующий шаг.
2. Данные Фамилии Имени и Отчества, которые вводятся при авторизации не передаются никуда кроме верхнго правого угла с ФИО пользователя
3. Загрузка формы идет от 2 до 5 минут. Из-за чего возникает ощущение, что данная задача не работает в принципе.
